In [13]:
import pandas as pd

weather_event_data = "Resources/WeatherEvents_Jan2016-Dec2021.csv"

weather_event_df = pd.read_csv(weather_event_data)

weather_event_df.head()

,EventId,Type,Severity,StartTime(UTC),EndTime(UTC),Precipitation(in),TimeZone,AirportCode,LocationLat,LocationLng,City,County,State,ZipCode
0,W-1,Snow,Light,2016-01-06 23:14:00,2016-01-07 00:34:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
1,W-2,Snow,Light,2016-01-07 04:14:00,2016-01-07 04:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
2,W-3,Snow,Light,2016-01-07 05:54:00,2016-01-07 15:34:00,0.03,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
3,W-4,Snow,Light,2016-01-08 05:34:00,2016-01-08 05:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
4,W-5,Snow,Light,2016-01-08 13:54:00,2016-01-08 15:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0

In [14]:
# parsing out dates
new = weather_event_df["StartTime(UTC)"].str.split("-", n = 2, expand = True)
# new column for year from start of weather event
weather_event_df["year"]= new[0]
# new column for month
weather_event_df["month"]= new[1]
#parse out portion of date not needed.
weather_event_df["junk"]= new[2]
# drop junk.
weather_event_df.drop(columns =["junk"], inplace = True)
# did it work? yes.
weather_event_df.head()

,EventId,Type,Severity,StartTime(UTC),EndTime(UTC),Precipitation(in),TimeZone,AirportCode,LocationLat,LocationLng,City,County,State,ZipCode,year,month
0,W-1,Snow,Light,2016-01-06 23:14:00,2016-01-07 00:34:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01
1,W-2,Snow,Light,2016-01-07 04:14:00,2016-01-07 04:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01
2,W-3,Snow,Light,2016-01-07 05:54:00,2016-01-07 15:34:00,0.03,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01
3,W-4,Snow,Light,2016-01-08 05:34:00,2016-01-08 05:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01
4,W-5,Snow,Light,2016-01-08 13:54:00,2016-01-08 15:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01

In [26]:
# dropping columns we don't need
master_df = weather_event_df[['Type','Severity','Precipitation(in)','AirportCode','LocationLat','LocationLng','City','County','State','ZipCode','year','month']]
master_df = pd.DataFrame(master_df)
master_df

,Type,Severity,Precipitation(in),AirportCode,LocationLat,LocationLng,City,County,State,ZipCode,year,month
0,Snow,Light,0.00,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01
1,Snow,Light,0.00,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01
2,Snow,Light,0.03,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01
3,Snow,Light,0.00,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01
4,Snow,Light,0.00,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01
...,...,...,...,...,...,...,...,...,...,...,...,...
7479160,Storm,Severe,0.00,KBVR,42.5833,-108.2833,Lander,Fremont,WY,82520.0,2021,12
7479161,Snow,Light,0.02,KBVR,42.5833,-108.2833,Lander,Fremont,WY,82520.0,2021,12
7479162,Snow,Light,0.08,KBVR,42.5833,-108.2833,Lander,Fremont,WY,82520.0,2021,12
7479163,Snow,Moderate,0.09,KBVR,42.5833,-108.2833,Lander,Fremont,WY,82520.0,2021,12
7479164,Snow,Light,0.01,KBVR,42.5833,-108.2833,Lander,Fremont,WY,82520.0,2021,12

In [17]:
# dataframe of weather types
Type_df = weather_event_df.drop_duplicates(["Type"]).reset_index(drop=True)[["Type"]]
Type_df = pd.DataFrame(Type_df.rename(columns={'Type':'Weather_Type'}))
Type_df

    Weather_Type
0           Snow
1            Fog
2           Cold
3          Storm
4           Rain
5  Precipitation
6           Hail

In [22]:
# Datframe with airport code and corresponding location data
location_df = weather_event_df.drop_duplicates(["AirportCode", "LocationLat", "LocationLng", "City", "State", "ZipCode"]).reset_index(drop=True)[["AirportCode", "LocationLat", "LocationLng", "City", "State", "ZipCode"]]
location_df = pd.DataFrame(location_df)
location_df

     AirportCode  LocationLat  LocationLng             City State  ZipCode
0           K04V      38.0972    -106.1689         Saguache    CO  81149.0
1           KAXS      34.6986     -99.3381            Altus    OK  73521.0
2           KAEL      43.6822     -93.3722       Albert Lea    MN  56007.0
3           KBTR      30.5378     -91.1468      Baton Rouge    LA  70807.0
4           KCMY      43.9581     -90.7397           Sparta    WI  54656.0
...          ...          ...          ...              ...   ...      ...
2066        KE33      36.9000    -106.5833            Chama    NM  87520.0
2067        KH21      37.9740     -92.6910        Camdenton    MO  65020.0
2068        KB23      40.6000    -116.8667  Battle Mountain    NV  89820.0
2069        KARL      41.6000    -106.2100       Rock River    WY  82083.0
2070        KBVR      42.5833    -108.2833           Lander    WY  82520.0

[2071 rows x 6 columns]

In [19]:
#Dataframe of severity types
severity_df = weather_event_df.drop_duplicates(["Severity"]).reset_index(drop=True)[["Severity"]]
severity_df = pd.DataFrame(severity_df)
severity_df

   Severity
0     Light
1    Severe
2  Moderate
3     Heavy
4       UNK
5     Other

In [25]:
# Dataframe consisting of Weather typr, Severity, Precip, year, and month
weather_df = weather_event_df[["AirportCode","Type", "Severity", "Precipitation(in)", "year", "month"]]
weather_df = pd.DataFrame(weather_df)
weather_df

        AirportCode   Type  Severity  Precipitation(in)  year month
0              K04V   Snow     Light               0.00  2016    01
1              K04V   Snow     Light               0.00  2016    01
2              K04V   Snow     Light               0.03  2016    01
3              K04V   Snow     Light               0.00  2016    01
4              K04V   Snow     Light               0.00  2016    01
...             ...    ...       ...                ...   ...   ...
7479160        KBVR  Storm    Severe               0.00  2021    12
7479161        KBVR   Snow     Light               0.02  2021    12
7479162        KBVR   Snow     Light               0.08  2021    12
7479163        KBVR   Snow  Moderate               0.09  2021    12
7479164        KBVR   Snow     Light               0.01  2021    12

[7479165 rows x 6 columns]